### ISSUE TITLE
Custom services used in the Playground project should be implemented in the Shared project

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1027]
Since the Playground project is a dual-mode Blazor project, the custom services used inside the blazor project should be implemented in a separate project (like the Shared project) in order to be registered correctly in both Api and Web projects to support both Client and Server mode of the Blazor.

**Comment by ysmoradi** [comment]
Imagine a service that is located in the web project.
In Blazor server, we run the web project and the service is located in the web project, no problem at all.
In Blazor client (wasm), we run the API project which has reference to the web project, again we've no problem.
The only thing that we need to do, is register that service in API project too in [#if BlazorClient section](https://github.com/bitfoundation/bitframework/blob/develop/src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Api/Startup.cs#L23-L33)
