### ISSUE TITLE
Paging/ Filtering and Sorting in Repository for WebAPI

### ISSUE THREAD

**Issue by behzad888** [bitfoundation/bitframework#110]
Do you have any idea to implement pagination options?

I have been used [SharpRepository](https://github.com/SharpRepository/SharpRepository/tree/develop/SharpRepository.Repository/Queries) query options, It's very useful.

**Comment by ysmoradi** [comment]
We already have support for OData on top of both asp.net & asp.net core with swagger functionality included. It supports paging/filtering/sorting/aggregation/grouping in a standard way, so there are lots of rad stuffs out there with odata support, for example dev express js & kendo js have support for odata. We also have a code generator which generates client side proxy for you automatically. Check https://docs.bit-framework.com/docs/bit-server-side/odata.html and https://github.com/ysmoradi/BitSampleApp

**Comment by behzad888** [comment]
Thanks for your time, but I meant `Web API`. I cannot use OData actually.
I want to know. Do you have any plan for paging/filtering/sorting on top of the repository in the core section for web API scenarios?

**Comment by ysmoradi** [comment]
Unfortunately no. But I know kendo has something for this. You can use it on server side, without using that in client side.

**Comment by ysmoradi** [comment]
Why you can't use OData?

**Comment by behzad888** [comment]
because We have an integration between multiple old modules and our accessibility is limited to change all parts, We can just change the UI part!
