### ISSUE TITLE
There is a lot of space next to the icon in some of BitComponents

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#1102]
I checked the Bit component out of the playground project and there is a lot of space next to the icon in BitActionButton, disabled BitRating because of the width of `bit-icon`.

Now they look this:

![space](https://user-images.githubusercontent.com/46419023/142753384-6a4e31b5-ee41-4bf6-ac9e-d92d94ce4802.JPG)

**Comment by maryamhdr** [comment]
This issue has been solved.
