### ISSUE TITLE
BitDropDown pop-up height

### ISSUE THREAD

**Issue by khashayar-pakkhesal** [bitfoundation/bitframework#1142]
The consumer must be able to set heigh for BitDropDown pop-up and it must be scrollable 
![image](https://user-images.githubusercontent.com/46280312/145002203-7dd8e5e6-016f-4423-bf33-40262a61e413.png)

**Comment by maryamhdr** [comment]
The consumer can easily customize the style of the drop-down callout and change the value of the `height`, `overflow`, or any other CSS properties of it.

@msynk what do you think?
