### ISSUE TITLE
 EF7 (RC1) - Cannot Skip() and Take() in SQL Server 2008

### ISSUE THREAD

**Issue by behzad888** [bitfoundation/bitframework#116]
I'm getting the error Incorrect syntax near 'OFFSET'. Invalid usage of the option NEXT in the FETCH statement. because SQL Server 2008 doesn't recognize it. 

So, based on aspnet/EntityFrameworkCore#4616 I think [this](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/Bit.Data.EntityFrameworkCore/Implementations/SqliteDbContextObjectsProvider.cs#L29) method should be changed!?

**Comment by ysmoradi** [comment]
? You're mentioning some code in SqliteDbContextObjectsProvider which is related to Sqlite, not Sql server, I can't get it!

**Comment by ysmoradi** [comment]
It has nothing to do with Offset/Next/Fetch etc. Could you please provide me more details?
This code only provides a connection to ef core context options.

**Comment by behzad888** [comment]
We implement paging option for web API on top of repositories. When we use Take and Skip methods of Dynamic.Linq dependency we got Offset/Next/Fetch etc. problem in Invoke `UseSqlServer` method.

I use `dbContextOptionsBuilder.UseSqlServer(c => c.UseRowNumberForPaging())` it works

**Comment by pataoftnahiara** [comment]
hello help please  in error "SqlException: Sintaxis incorrecta cerca de 'OFFSET'."

**Comment by ysmoradi** [comment]
> hello help please in error "SqlException: Sintaxis incorrecta cerca de 'OFFSET'."

https://github.com/bitfoundation/bitframework/issues/116#issuecomment-413488749

**Comment by behzad888** [comment]
UseRowNumberForPaging has been removed  EF Core 3.x

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#userownumberforpaging-has-been-removed
