### ISSUE TITLE
Incorrect sample code in BitButton demo page

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#1172]
- in the BitButton sample code there is a closing tag for a label that writhe `<label/>` instead of `</label>`.
- in the visibility section of BitButton, there is a Hidden attribute that does not exist and should use `Visibility `instead.
- there is a missing close angle for BitButton in the "Arias for Screen Reader" section.
- there is no unclosing tag for the span element in the "Button-like Anchor" section.

**Comment by saeedhalab** [comment]
I checked that this problem has already been fixed
