### ISSUE TITLE
Incorrect sample code in the BitDropDown demo page

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#1209]
- there is extra closing angles in the two first code sample elements
- there must use `BitDropDownItem` instead of `dropdownitem` in the sample code block.
- in the sample code block it's better to use a new c# code structure, and use `new()` instead of `new BitDropDownItem()` in list items codes.
- in the sample code block must use `BitDropDownItemType` instead of `DropDownItemType`.
- in the sample code block must use `IsEnabled = false` instead of `IsEnabled = "false"`
- there is a missing `return items;` in the sample code block in the `GetDropdownItems()` method in the first sample code.
- change `private string ControlledSelectedMultipleKeys` to `private List<string> ControlledSelectedMultipleKeys` in the sample code block code of Controlled Multi-Select section.
- `newDropDownItemData `must change to `new DropDownItemData` in sample code block.

**Comment by maryamhdr** [comment]
This issue is solved.
