### ISSUE TITLE
Lost EfCoreRepository methods

### ISSUE THREAD

**Issue by behzad888** [bitfoundation/bitframework#124]
There is no method based on [documentation](https://docs.bit-framework.com/introduction/data-access) as the name as 'GetCollectionQuery' in 'EfCoreRepository'.
Please review [this change](https://github.com/bit-foundation/bit-framework/commit/8195b28b51c8d1b9f9c73681124d441f36fa8617#diff-71501cd5a2c996e8b4789052426a7607)

And Do you have any plan or document to implement SQL raw queries?

**Comment by ysmoradi** [comment]
We're going to bring back that method. Thanks for your attention.
We know what's RawSqlQuery, but could you please provide more info about your requirement?
