### ISSUE TITLE
کامپوننت تاریخ شمسی در Blazor

### ISSUE THREAD

**Issue by shahab2025** [bitfoundation/bitframework#1295]
سلام 
من از کامپوننت شما برای بلیزر استفاده میکنم
میخواهم تقویم فارسی داشته باشم و بایند هم بشود
ولی وقتی بایند را به سیستم اضافه میکنم خطا میدهد 
این نمونه کد شماست 

```
<BitDatePicker @bind-Value="@selectedDate" Style="width: 300px"></BitDatePicker>
<BitLabel>this is selected date: @selectedDate.ToString()</BitLabel>
@code {
        private string selectedDate ="";
}

```

و این خطای کامپایلی 

`
Error	CS1503	Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<System.DateTimeOffset>' to 'Microsoft.AspNetCore.Components.EventCallback'`

البته من تایپ متغیر را هم DateTimeOffset گذاشتم درست نشد 

لطفا مرا راهنمایی فرمائید 
ایمیل من 
Shahab2025@gmail.com

متشکرم

**Comment by ysmoradi** [comment]
Please use DateTimeOffset? instead of DateTimeOffset
We're reviewing our components API to make sure they have suitable developer experience
