### ISSUE TITLE
Implement a control mechanism in order to config Blazor for the output type

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1355]
we need a specific mechanism for the web app of the project template to guide the Blazor build pipeline to create an output with the following attributes:

- PWA
- PrerenderEnabled
- Default

**Comment by ysmoradi** [comment]
What would be a variable name?
I'd recommend Default instead of Normal
WebAppKind would be a good name in my opinion.
Remember that this is for the project template. Bit components playground would be pre render enabled for sure.

**Comment by msynk** [comment]
I agree with the change of `Normal` to `Default`, it's a better name.
about the variable name I'm not happy with the suggested name (`WebAppKind`), this variable is not going to determine the `Kind` of the the app. maybe something like `WebAppOutputType` is a better name.

**Comment by ysmoradi** [comment]
What about WebAppType? PWA, PreRendererEnabled, SPA

**Comment by ysmoradi** [comment]
@msynk PING!

**Comment by msynk** [comment]
I think `WebAppType` has the same issue. 
IMO this variable will indicate the type of output that the app is going to produce. that's why I suggested those names.

**Comment by msynk** [comment]
what about `WebAppOutputProperty`?

**Comment by ysmoradi** [comment]
WebAppDeploymentType ? @msynk
SPA | PreRendererEnabled | PWA

**Comment by msynk** [comment]
I think `WebAppDeploymentType` is a good enough name :)
btw, all of the blazor apps are actually a type of SPA, so using `SPA` as one of the options is weird IMO.

**Comment by ysmoradi** [comment]
I do agree, but let's do this (";
