### ISSUE TITLE
Add RadioButtonGroup component

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitframework#1372]
Add RadioButtonGroup component. The RadioButtonGroup component is like a ChoiceGroup in UI, and like BitDropDown in the api, so you can create a list of RadioButton items and send them to RadioButtonGroup.

**Comment by msynk** [comment]
this component is already been implemented by renaming the old `BitChoiceGroup` #1400 (#1713)
so I'm closing it.
