### ISSUE TITLE
use minimal api for playground project

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1378]
convert the current implementation of the program/startup configuration into the new minimal API of .net 6

**Comment by ysmoradi** [comment]
Don't forget that every project configuration change should gets applied in both Playground & ToDoTemplate projects to keep them in sync.

**Comment by msynk** [comment]
yeah I know, that's why I mentioned only the Playground project in this issue. 
the TodoTemplate one will be submitted in another issue.
