### ISSUE TITLE
how can give select date? 

### ISSUE THREAD

**Issue by hamidish** [bitfoundation/bitframework#159]
how can i get select data when clicked   . in xamarin form.

**Comment by hamidish** [comment]
when i select date year not converto to shamsi?

**Comment by ysmoradi** [comment]
In xamarin forms, Entry has a Text property, you can either bind it to a property in View Model or you can read it in view's code behind.
BitDatePicker has a property called SelectedDateTime and you can convert that date time to shamsi date using PersianCalendar class.

**Comment by hamidish** [comment]
when i use selecteddate and binding autoclose not worked

**Comment by ysmoradi** [comment]
Which version do you use? Could you please provide me a repo? (Source code which re produces this issue)

**Comment by hamidish** [comment]
i use version 2.4.3.
when i use   SelectedDateTime="{Binding Path=SelectedDateTime}". autoclose not worked.
and when i select data . when closed. the year is not shamsi its .

**Comment by hamidish** [comment]
Unhandled Exception:

System.IndexOutOfRangeException: There is not page in PopupStack occurred

**Comment by ysmoradi** [comment]
Could you please check our sample project? It should work as expected.
About the error you mentioned, you can install CI version of Rg.Plugin.Popup by having following Nuget.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="rg-plugin-popup" value="https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99" />
  </packageSources>
</configuration>
``` 
Then install following into your project:
```
<PackageReference Include="Rg.Plugins.Popup" Version="1.1.5.210" />
```
