### ISSUE TITLE
Remove HTML's default reveal password (eye) button from BitTextField component

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1618]
**Describe the bug**
The HTML's default reveal password (eye) button is conflicting by custom reveal button of password type `BitTextField` component

**Expected behavior**
The HTML's default reveal password (eye) button is better to be removed

| `Current state` | `Expected behavior` |
|--------|--------|
|  ![ezgif-5-da139c5523](https://user-images.githubusercontent.com/29206777/157288593-1ed5e25f-c4d5-4f29-b971-4fa32dcd0451.gif) | ![ezgif-5-1a3afdd94f](https://user-images.githubusercontent.com/29206777/157288614-829f29be-9e34-41ae-ae8f-2b1c84b1088c.gif) |

**Comment by msynk** [comment]
I'm not seeing this issue on my machine on any browser. is this requires a special condition?

**Comment by RezaKargar** [comment]
I'm using the `Edge chromium` browser,
I double checked, the problem is in mobile browser too.
But not in Chrome, I haven't check the Firefox

**Comment by msynk** [comment]
I've checked the edge docs and also tried it again today and found out that we have this issue in some situations.
so I'm going to triage this issue.
