### ISSUE TITLE
Implement Confirm Email process in TodoTemplate

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1671]
Currently, the `Confirm Email` process is not implemented in the TodoTemplate project at all. it is required to implement such a process in a boilerplate project such as TodoTemplate.
For now, it is required to have the base implementation of this process in the server+client, and the final UI enhancements based on new designs will be taken care of in the future.

**Comment by maryamhdr** [comment]
this issue has been resolved.
