### ISSUE TITLE
BitRating problems in data-is-current and tabindex attributes

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1737]
When a value of a `BitRating` component changes the **data-is-current** attribute must be **true** for **button** tag of that specific item and also the **tabindex** must be 0 for it and -1 for all other items

**Comment by msynk** [comment]
@maryamhdr
plz investigate this issue

**Comment by maryamhdr** [comment]
plz add some tests for these enhanced features too.
