### ISSUE TITLE
ShowMore and dismiss buttons problem in BitMessageBar

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1753]
In `BitMessageBar` component when `Truncated` and `OnDismiss` properties both got value then the related buttons get so close to each other and makes mobile user to click on show more button

| **Current State** | **Expected State** |
|--------|--------|
|    ![image](https://user-images.githubusercontent.com/29206777/159894689-6172b059-0c0b-4df6-9d70-552d8d0a027c.png)    |    ![image](https://user-images.githubusercontent.com/29206777/159894554-2ab7a0e7-9273-4dfc-8245-0ec3cc1b2538.png)    |

**Comment by msynk** [comment]
@maryamhdr 
plz investigate this issue 😊

**Comment by maryamhdr** [comment]
> @maryamhdr plz investigate this issue 😊

This issue is valid 👍🏻
