### ISSUE TITLE
BitToggle of 'show preview box' in BitColorPicker demo does not work properly

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1755]
In [demo example 1](https://bitcomponents.azurewebsites.net/components/color-picker#example1) of `BitColorPicker` component demos, the corresponding `BitToggle` for showing/hiding preview box does not work properly

**Comment by msynk** [comment]
@maryamhdr 
plz investigate

**Comment by maryamhdr** [comment]
> @maryamhdr plz investigate

This issue is valid. I think the reason is that we have changed the input components for validation.
