### ISSUE TITLE
RadioButton style problem in small screens in both the `BitRadioButtonGroup` and the `BitRadioButtonList` components

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1756]
The styles of **RadioButtons** in `RadioButtonGroup` and `RadioButtonList` components has problems in small screen devices

| **RadioButtonList** | **RadioButtonGroup** |
|--------|--------|
|    ![image](https://user-images.githubusercontent.com/29206777/159899875-aff6dc96-edb3-4096-807a-7bb1602c8eaf.png)    |    ![image](https://user-images.githubusercontent.com/29206777/159899882-43f6be4d-0de3-4f4a-9f9d-8dcfd9597b81.png)    |

**Comment by msynk** [comment]
@maryamhdr 
plz investigate

**Comment by maryamhdr** [comment]
> @maryamhdr plz investigate

This issue is valid and has been triaged 👍🏻

**Comment by saeedhalab** [comment]
I checked this issue and the component styles are not a problem, the problem is the style of the component ExampleBox

**Comment by msynk** [comment]
@maryamhdr 
plz investigate the issue again, and update the issue if requried.
