### ISSUE TITLE
Style issues of the `BitDatePicker` in small screen

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1757]
For `BitDatePicker` in small devices which has callout for month must hide the month callout 

**Note:** The Below images are for small screen devices
| **Current State** | **Expected State** |
|--------|--------|
|   ![image](https://user-images.githubusercontent.com/29206777/159900495-3afc4990-abd4-445f-87fd-1b318c246ae1.png)   |  ![image](https://user-images.githubusercontent.com/29206777/159900848-f36f3de4-82a8-4345-a0aa-92fb340379fa.png)  |

**Comment by RezaKargar** [comment]
@Cyrus-Sushiant  Have you solved this issue in #1746 ?
If so please close this issue

**Comment by msynk** [comment]
@maryamhdr 
plz investigate

**Comment by maryamhdr** [comment]
> @maryamhdr plz investigate

This issue is valid.
The `BitDatePicker` component responsive view has not been developed yet :)
