### ISSUE TITLE
Wrong error message for incorrect password in sign-in of TodoTemplate

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1766]
In **sign-in** page of `TodoTemplate` when the password is incorrect the displayed error message is for **user not found**

| **Current State** | **Expected State** |
|--------|--------|
|      This 'test@test.com' exits but the given password is incorrect      |           |
|  ![image](https://user-images.githubusercontent.com/29206777/160177694-a29f5602-b988-46be-b4fc-88ccd624e447.png)  |    ![image](https://user-images.githubusercontent.com/29206777/160178133-b5748e9c-3d5c-455b-834d-fb9762887c5c.png)    |

**Comment by ysmoradi** [comment]
This is by design
