### ISSUE TITLE
Catch error of email sending failure in TodoTemplate

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1769]
When a failure happens during sending email for user confirmation or password reset, the Api does not catch that failure exception in proper way that client knows,
so the user is not properly aware of the problem

**Comment by ysmoradi** [comment]
Do we return the Ok status code in such a scenario?

**Comment by RezaKargar** [comment]
> Do we return the Ok status code in such a scenario?

No, The Api returns `500 Internal Server Error`

![image](https://user-images.githubusercontent.com/29206777/160241164-566b9254-6f1d-4316-9d8f-00a97be3c6a5.png)

**Comment by ysmoradi** [comment]
That's fine, what are you looking for?

**Comment by RezaKargar** [comment]
Isn't better we let the client know that there is some failure?

**Comment by ysmoradi** [comment]
It's a UX concern. Let's @maryamhdr decide about this.

**Comment by maryamhdr** [comment]
> When a failure happens during sending email for user confirmation or password reset, the Api does not catch that failure exception in proper way that client knows, so the user is not properly aware of the problem

Let's talk about this issue too 👍🏻

**Comment by RezaKargar** [comment]
As my talk with @maryamhdr this is not a UX thing, 
In exception handling of the `DoSignUp` in [SignUp.razor.cs](https://github.com/bitfoundation/bitframework/blob/b3b83c1a1e43312e8215dca31ff607df94265cb9/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs) we only catch **ResourceValidationException**
and **KnownException** and the Email sending failure is an **Exception** which we do not catch:

https://github.com/bitfoundation/bitframework/blob/b3b83c1a1e43312e8215dca31ff607df94265cb9/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs#L96-L107

**Comment by ysmoradi** [comment]
I've already discussed this with @msynk 
We've nothing to do with unknown exceptions in our pages and we only handle specific exceptions in our pages.
The remaining exceptions will go through global exception handling and at there, we can show toast for all of them
We can also log those exceptions later.
@RezaKargar @maryamhdr
