### ISSUE TITLE
Not a valid calendar for the given calture

### ISSUE THREAD

**Issue by RezaShaban** [bitfoundation/bitframework#177]
**Describe the bug**
i use 
VS 2017
XF 4.3.0.991221
Bit.CsharpClient.Controls 3.1.0

i copied codes from sample project

             xmlns:uc="https://bit-framework.com"
             xmlns:noda="clr-namespace:NodaTime;assembly=NodaTime"

<uc:BitDateTimePicker Text="لطفا یک روز را انتخاب کنید" Culture="Fa" DateTimeDisplayFormat="dd MMM yyyy" 
                              CalendarSystem="{x:Static noda:CalendarSystem.PersianArithmetic}"
                              FlowDirection="RightToLeft" SelectedDateTime="{Binding SelectedDate}"/>

**To Reproduce**
init in mainactivity and app.cs

**Comment by ysmoradi** [comment]
Could you please provide stack trace of exception?
