### ISSUE TITLE
Support of submitting the forms by pressing Enter key in TodoTemplate

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#1770]
Support of submitting the **SignUp/Signin/ResetPassword/ForgotPassword** forms by pressing the **Enter** key is good for user experience

**Comment by saeedhalab** [comment]
When we use EditForm on the page,  automatically supports the form by pressing Enter key you can follow this link 
[https://github.com/dotnet/aspnetcore/issues/16666](url)

**Comment by ysmoradi** [comment]
So, shall we close this issue? @maryamhdr

**Comment by maryamhdr** [comment]
> When we use EditForm on the page, automatically supports the form by pressing Enter key you can follow this link [dotnet/aspnetcore#16666](https://github.com/dotnet/aspnetcore/issues/16666)

So this issue is not valid anymore.
