### ISSUE TITLE
Privacy checkbox issue of the sign up page in ProjectTemplate

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitframework#1773]
The privacy checkbox doesn't work correctly. When the user clicks on it, the bound boolean value to it doesn't change and remains `false`.

**Comment by RezaKargar** [comment]
@maryamhdr I can take care of this in case you are busy

**Comment by maryamhdr** [comment]
> @maryamhdr I can take care of this in case you are busy

Yeah sure :)
I'll assign it to you 👍🏻
