### ISSUE TITLE
SelectedDateTime in Solar System

### ISSUE THREAD

**Issue by omid-ahmadpour** [bitfoundation/bitframework#178]
** Wrong SelectedDateTime in Solar System**
In Solar date when select a date from Calender it doesn't select a solar date.
It wrongly bind Gregorian date
for more detail i select a solar date:
![SelectedDateTime](https://user-images.githubusercontent.com/42376112/71321207-9087c780-24cb-11ea-8d92-62f02ea699b2.jpg)
And it wrongly bind a Gregorian date

![XamlSelected](https://user-images.githubusercontent.com/42376112/71321213-a5fcf180-24cb-11ea-9e13-992afdfae913.JPG)

**Comment by ysmoradi** [comment]
It's working as expected. Why do you need this?

**Comment by ysmoradi** [comment]
You should declare your property as a date time
