### ISSUE TITLE
Incorrect month change buttons in BitDatePicker

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitframework#1810]
If BitDatePicker is used in an EditForm, when clicking on the month change buttons will submit the form.
![image](https://user-images.githubusercontent.com/29052211/160653311-03063ad8-aaee-47d7-b7e4-cdf0a2cb5efc.png)

**Comment by maryamhdr** [comment]
This issue has not been triaged yet!!!
Why have you sent a PR for this issue?!
@Cyrus-Sushiant

**Comment by Cyrus-Sushiant** [comment]
> This issue has not been triaged yet!!!
> Why have you sent a PR for this issue?!
> @Cyrus-Sushiant 

Sorry, I thought there was in high priority and I sent PR for that.
