### ISSUE TITLE
Incorrect style in BitPersona component

### ISSUE THREAD

**Issue by saeedhalab** [bitfoundation/bitframework#1828]
in this issue missing "t" in  primaryText class name

![persona](https://user-images.githubusercontent.com/61748672/161426308-b8a43c44-bf8c-476d-9452-8f9eb59089c5.png)

**Comment by maryamhdr** [comment]
> in this issue missing "t" in primaryText class name

the class name is totally incorrect and doesn't match our naming convention.
We must not have any capital case characters in our class names.
