### ISSUE TITLE
Modify GetStarted page content in playground project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitframework#1845]
In the bit component GetStarted page where we add style & script, we must add the `_Layout.cshtml` file as one of the files we can add the snippet too.

![freesnippingtool com_capture_20220406162849](https://user-images.githubusercontent.com/48528003/161969971-012efd38-05ed-4705-8b75-0006ab2fba2e.png)

**Comment by maryamhdr** [comment]
Is this issue the one you have mentioned in https://github.com/bitfoundation/bitframework/pull/1835#discussion_r843156494?
@ysmoradi

**Comment by ysmoradi** [comment]
Yup! @maryamhdr
