### ISSUE TITLE
Missing `Confirm Password` field in the SignUp page of the TodoTemplate project

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1864]
Having a `Confirm Password` on a signup page is almost mandatory, and since this field is missing from the SignUp page of the TodoTemplate project, it's better to add it ASAP.

**Comment by maryamhdr** [comment]
> Having a `Confirm Password` on a signup page is almost mandatory, and since this field is missing from the SignUp page of the TodoTemplate project, it's better to add it ASAP.

We have checked the user experience of adding this field. It is not recommended to have a `confirm password` field based on UX best practices. So, We removed this field.
@msynk

**Comment by msynk** [comment]
Since this feature is a bad UX practice nowadays, I'm closing this issue.
