### ISSUE TITLE
Bad experience in sign-up and email confirmation in Todo Template project

### ISSUE THREAD

**Issue by mohabbati** [bitfoundation/bitframework#1866]
In sign-up by email, we send an email for confirmation to the user. In sending emails, we check for too many send emails.

The problem is:
When a user signs up by a specific email we generate a token to confirm her email. If she submits again for that email at the time, we generate another token and the previous token expires automatically, and we never send her a new email for confirmation. So, she never can confirm her email until she submits it again after a while.

**Comment by msynk** [comment]
@mohabbati plz update this issue as we discussed before😊
