### ISSUE TITLE
Add Apple OAuth

### ISSUE THREAD

**Issue by mohabbati** [bitfoundation/bitframework#187]
Users who use iOS can register and login to applications easily. So, they login with their AppleID.

**Comment by mehrandvd** [comment]
Could you provide more information about your requirement?

**Comment by mohabbati** [comment]
Users who use iOS can register and login to applications easily. So, they login with their AppleID.

**Comment by mohabbati** [comment]
> Could you provide more information about your requirement?
Users who use iOS can register and login to applications easily. So, they login with their AppleID.
