### ISSUE TITLE
Change the type of primary key in the `TodoTemplate` project

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitframework#1870]
Use the long instead of int for the type of primary key in identity tables and other tables because int has range limitations and is not suitable for large projects.

**Comment by maryamhdr** [comment]
> Set the table primary key to long, due to integer range.

Can you provide more information about this issue?
tnx ;)
@Cyrus-Sushiant

**Comment by msynk** [comment]
@Cyrus-Sushiant :
what table(s)? as @maryamhdr commented before, plz provide more information

**Comment by Cyrus-Sushiant** [comment]
Based on the conversation we had with @msynk, cause of the limited records of the ToDoTemplate project, there is no need to change the type of primary key to long.
