### ISSUE TITLE
No implementation for IDependencyResolver is registerd

### ISSUE THREAD

**Issue by pharazfadaei** [bitfoundation/bitframework#189]
In order to resolve registered dependencies by name, I use an instance of IDependencyManager in my services. But IDependencyManager provides register functionalities as well that I don't intend -and as the container is already built at this stage, probably am not supposed- to use. All I need is the functionalities that IDependencyResolver provides. But the problem is IDependencyResolver does not get injected. It would be nice if you register AutofacDependencyManager as an implementation of IDependencyResolver as well!

**Comment by ysmoradi** [comment]
You could inject IServiceProvider

**Comment by PharazFadaei** [comment]
How can I use IServiceProvider to resolve a named dependency?

**Comment by ysmoradi** [comment]
> How can I use IServiceProvider to resolve a named dependency?

Good question! ;D
Let me check a few things first!

**Comment by msynk** [comment]
any updates?
