### ISSUE TITLE
Implement the `404 Error` page in the `playground` project

### ISSUE THREAD

**Issue by maryamhdr** [bitfoundation/bitframework#1891]
The `404 Error` page must be implemented based on the new UI/UX design.

**Comment by msynk** [comment]
which project?

**Comment by ysmoradi** [comment]
Due to the fact that we can't re-use the same 404 not found page between components playground and project template, I'd prefer having two separate issues for this

**Comment by maryamhdr** [comment]
> which project?

I've updated the issue title. thank you :)
