### ISSUE TITLE
Definition button type in the `BitBreadcrumb`

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitframework#1903]
Definition of the type of HTML button to `button` type in the `BitBreadcrumb`. Because the type of button is not specified and is in a form, clicking on it will cause the form to be submitted.

**Comment by ysmoradi** [comment]
We had the same issue with date picker. Could you please search for button usage in all our components in order to make sure this issue is completely resolved? @Cyrus-Sushiant

**Comment by Cyrus-Sushiant** [comment]
> Could you please search for button usage in all our components in order to make sure this issue is completely resolved?

Yes, sure
