### ISSUE TITLE
Automatic Sign-In after the confirm email in `TodoTemplate` project

### ISSUE THREAD

**Issue by sajadkardel** [bitfoundation/bitframework#1927]
The email confirmation page contains a condition that redirects to the sign-in page if the email was confirmed.
But this approach is wrong Because we have to sign in automatically after the confirmed email.

**Comment by ysmoradi** [comment]
@msynk ?

**Comment by msynk** [comment]
I'm not sure if this issue is actually valid. I'll discuss it with @maryamhdr

**Comment by maryamhdr** [comment]
> I'm not sure if this issue is actually valid. I'll discuss it with @maryamhdr

Based on UX best practices, it's a good experience for the user to be signed in right after his/her email is confirmed.
@ysmoradi @msynk

**Comment by msynk** [comment]
It is a very bad security hole to have this feature.
the user needs to actually enter their username/password to log in.
