### ISSUE TITLE
 Rename  ``TodoTemplate.Infra``  project to  ``TodoTemplate.Iac``  (Infra as code) in  ``TodoTemplate``  solution

### ISSUE THREAD

**Issue by msangtarash** [bitfoundation/bitframework#1948]
The name of ``TodoTemplate.Infra`` should be changed to ``TodoTemplate.Iac``

**Comment by msynk** [comment]
@msangtarash 
please provide enough amount of description in this issue for others to understand what's the problem.
and mention what project is this issue for (at least in the title), we have 3 major projects atm.
and also add the appropriate labels to the issue.

**Comment by msangtarash** [comment]
The name of ``TodoTemplate.Infra`` should be changed to ``TodoTemplate.Iac``
