### ISSUE TITLE
How Can Selected Date Value From User And Pass To Code Behind In XAMARIN FORMS

### ISSUE THREAD

**Issue by alinouri1989** [bitfoundation/bitframework#195]
```xml
<bit:BitDateTimePicker
                                CalendarSystem="{x:Static noda:CalendarSystem.PersianArithmetic}"
                                Culture="Fa"
                                DateTimeDisplayFormat="yyyy/MM/dd"
                                AutoClose="True"
                                ShowTimePicker="False"
                                SelectedColor="Black"
                                TodayColor="DeepPink"
                                FlowDirection="RightToLeft"
                                FontFamily="{StaticResource Persian-Solar-Calendar-FontFamily}"
                                Text="Sell Date" />
```
```cs
private void AddHeaderSell_Clicked(object sender, EventArgs e)
        {
            InsertSellHeaderViewModel = new InsertSellHeaderViewModel()
            {
                IdBuyResource = CustomerSell.Id,
                Title = CustomerSell.Name.ToString(),
                DateSell = "Here Got DatePIcker Selected Date By User" // این قسمت توسط تاریخ انتخاب شده در DatePicker تکمیل گردد
                //تاریخ انتخاب شده توسط کاربر داخل این خصیصه قرار داده شود
            };

            SellHeaderCollection = new ObservableCollection<SellHeader>();
            foreach (var item in App.apiServiceManager.InsertHeaderSell(InsertSellHeaderViewModel).Result)
                SellHeaderCollection.Add(item);

            DgvHeaders.ItemsSource = SellHeaderCollection.Select(o => new { o.Id, o.Name, o.DateBuy });


        }
```

**Comment by ysmoradi** [comment]
Simply use x:Name on <bit:BitDateTimePicker x:Name="DateSellDateTimePicker"
and then in code behind use DateSellDateTimePicker.SelectedDateTime

**Comment by alinouri1989** [comment]
![CodeBehind](https://user-images.githubusercontent.com/51013386/87873674-ba10bf00-c9d8-11ea-9c64-b5e230c041ef.png)
![Xaml](https://user-images.githubusercontent.com/51013386/87873675-bb41ec00-c9d8-11ea-8e4a-671d93cb34c7.png)

I Got Error When Use X:Name in <bit:BitDateTimePicker> i send Error For You

**Comment by ysmoradi** [comment]
It seems to be an issue with custom namespace schema in xamarin forms
Use
xmlns:bit="clr-namespace:Bit.View.Controls;assembly=Bit.Client.Xamarin.Controls"
instead of 
xmlns:bit="https://bitframework.com"

I'd recommend you to use MVVM approach.
You can also take a look at followings:
https://www.dotnettips.info/learningpaths/details/77
Watch this video before reading those articles:

[Xamarin-Forms-Bit-Tutorial-Update.zip](https://github.com/bitfoundation/bitframework/files/4943706/Xamarin-Forms-Bit-Tutorial-Update.zip)

**Comment by alinouri1989** [comment]
I Like Working MVVM Architecture But I Not Use In All Page ,Tanks Alot, This Name Space Worked For Me,
I Replaced xmlns:bit="https://bitframework.com"
With xmlns:bit="clr-namespace:Bit.View.Controls;assembly=Bit.Client.Xamarin.Controls"
