### ISSUE TITLE
Improve all forms in `ToDoTemplate` project

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [bitfoundation/bitframework#1950]
Modify all forms in ToDoTemplate project. 
- If all fields are empty, the submit button is disabled.
- Set text-align left in error validation.
- Remove data annotation validation for checkbox

**Comment by msynk** [comment]
please submit separate issues for each of these problems.
submitting an issue to report multiple un-related problems is not a good practice, so I'm closing this issue.
