### ISSUE TITLE
Add BitText Component To BitComponents

### ISSUE THREAD

**Issue by MohammadJavadTabari** [bitfoundation/bitframework#1964]
let's first ask a question.
what is the benefit of using prebuild components like "Bit", "Mud", "Telerik" and like them?
they were built to make blazor development easier.
and someone like me chooses the one that is must easy-to-use components for building web apps and more like that.
so I prefer to add another component  to bit components, 
"BitText Component" that gives the user some options like "text type (h1, h2, ..)", "text color (using bit colors)", "popular fonts", "style"
, "class", "align" and ... .

**Comment by msynk** [comment]
I don't think adding this component is useful.
the developer can simply use any tag and apply any style that he/she wants for rendering a text.

**Comment by Cyrus-Sushiant** [comment]
> I don't think adding this component is useful. the developer can simply use any tag and apply any style that he/she wants for rendering a text.
> 
> @maryamhdr & @Cyrus-Sushiant what do you think?

I agree with you. In my opinion, using this component will not have any special consequences because you finally have to specify the type of output. (h1, h2, p, ...)

**Comment by MohammadJavadTabari** [comment]
@msynk @Cyrus-Sushiant @maryamhdr 
just put yourself in a backend .net developer position who wants to start using blazor, he/she is quite confused when working with fonts, colors, size, align, and more.
also, most popular components have this option.
now, what is your opinion?

**Comment by msynk** [comment]
a developer actually needs to have a general knowledge of HTML/CSS before working on a blazor project. so it's not a good enough reason to have such a simple component.
the only reason that comes to mind for such a component, is to have a unified theme for everything in a project, although it can be achieved simply by using the styling guidelines of the component library.
