### ISSUE TITLE
Add a new github action to publish Bit open source nightly packages to nuget.org

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#1966]
The nightly packages are required to be published from the develop branch, so a new Github action is needed to handle this publish and this new action should trigger only on pushing git tags.
the projects that need to be published in this Github action are as follows:
- bswup
- components

**Comment by ysmoradi** [comment]
- [ ] bit swup
- [ ] bit components
- [ ] bit source generators
- [ ] bit code analyzers
