### ISSUE TITLE
incorrect style submit button when submitting the form on the Sign-In page in the `TodoTemplate` project

### ISSUE THREAD

**Issue by saeedhalab** [bitfoundation/bitframework#1976]
When the form is submitted, the submit button must be disabled and prevented from being clicked again

like this image :

![sign-inssssss](https://user-images.githubusercontent.com/61748672/167273539-e846ea14-02eb-467b-9631-8de1e5dfc928.png)

**Comment by msynk** [comment]
duplicate of #1975
