### ISSUE TITLE
incorrect style submit button when submitting the form on the ForgotPassword page in the `TodoTemplate` project

### ISSUE THREAD

**Issue by saeedhalab** [bitfoundation/bitframework#1978]
When the form is submitted, the submit button must be disabled and prevented from being clicked again

like this image :

![forget-pass](https://user-images.githubusercontent.com/61748672/167274018-628e5819-85ad-48e2-84a5-60af292207b5.png)

**Comment by msynk** [comment]
duplicate of #1975
