### ISSUE TITLE
frame not work when using bit framework

### ISSUE THREAD

**Issue by mokhtarsoholi** [bitfoundation/bitframework#200]
hi,
i use bit framework for using datepicker but when install bit framework from nuget then frame in design not worked please see the attach images.
first image its befor install bit framework and second image its after that.

img1
![Screenshot (14)](https://user-images.githubusercontent.com/20678483/92244403-19b72100-eed8-11ea-9063-4b931909469a.png)

img2
![Screenshot (15)](https://user-images.githubusercontent.com/20678483/92244544-4bc88300-eed8-11ea-9912-3b2ff255cf28.png)

**Comment by ysmoradi** [comment]
Could you please submit a simple app which reproduces this?

**Comment by mokhtarsoholi** [comment]
i create new project and now its worked very well
but why in other project i have this problem?

**Comment by ysmoradi** [comment]
You've to make two projects identical step by step!
