### ISSUE TITLE
Swagger is only accessible in the development environment

### ISSUE THREAD

**Issue by milad-karimifard** [bitfoundation/bitframework#2052]
Currently, swagger is only enabled in development mode. I suggest enabling swagger without environmental conditions in order so we can use it in other environments such as staging for a better experience

**Comment by msynk** [comment]
@ysmoradi is it a correct decision to show the swagger UI without any authentication in production?
shouldn't we do something similar to what is explained in the following link to secure it?

https://medium.com/@niteshsinghal85/securing-swagger-in-production-92d0a045a5
