### ISSUE TITLE
Email setting is not fully detailed in appsetting.json

### ISSUE THREAD

**Issue by milad-karimifard** [bitfoundation/bitframework#2055]
Currently, the email setting in appsetting.json is not described fully detailed in all options belonging to the "EmailSettings" class. I suggest adding all options in appsetting.json

**Comment by msynk** [comment]
@milad-karimifard 
the only settings that are missing are `UserName` and `Password` and adding them in the appsettings file is a security risk.

**Comment by ysmoradi** [comment]
I think this improves the developer experience
Even if we deny adding this values in app settings by default, their corresponding CLR object at runtime would have either null or empty values
@msynk
