### ISSUE TITLE
how get date and time using bitframework datepicker

### ISSUE THREAD

**Issue by mokhtarsoholi** [bitfoundation/bitframework#210]
hi , i using your datepicker persian and it work very well but i cant use date and time when i open date and time picker and choose my date and time and then i need to save this time and date to variable how can i do?

**Comment by ysmoradi** [comment]
In MVVM approach, you can bind SelectedDateTime into DateTime or DateTimeOffset property, otherwise you can use x:Name (For example BirthDatePicker) and use BirthDatePicker.SelectedDateTime

**Comment by mokhtarsoholi** [comment]
do you have an example of it?

**Comment by ysmoradi** [comment]
https://github.com/bitfoundation/bitframework/tree/master/Samples/CSharpClientSamples/Controls.Samples

> i need to save this time and date to variable how can i do?

If you know how to save Entry's text property into variable, you can use the same approach for BitDateTimePicker's SelectedDateTime property.
