### ISSUE TITLE
Is there anyway to change text color of DateTimePicker?

### ISSUE THREAD

**Issue by nedoomoh** [bitfoundation/bitframework#211]
I want to change showing text color in DateTimePicker Button. By default, It's Black. Can I adjust it with any attribute?

**Comment by ysmoradi** [comment]
You can provide your own ui as following example:
https://github.com/bitfoundation/bitframework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples/BitDateTimePickerSampleView.xaml#L35-L56
