### ISSUE TITLE
Bit.Client.Web.BlazorTooling

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitframework#220]
Add Bit.Client.Web.BlazorTooling (Temporary name) to the src/Bit.Client.Web.BlazorUI.sln solution, next to "Bit.Client.Web.BlazorUI" project in "src\Client\Web" folder

Add C# 9 source generator to this project to address the following code generation requirement:

https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#implement-setparametersasync-manually

**Comment by msynk** [comment]
+1

**Comment by FarhadGhE** [comment]
Adding the solution and applying discussed changes to BitButton will be no more than 6 hours (can be less). I will address the issue on Thursday or Friday.
