### ISSUE TITLE
CI pipeline for Bit.Client.Web.BlazorUI

### ISSUE THREAD

**Issue by ysmoradi** [bitfoundation/bitframework#221]
Add required YAML pipelines to make sure Bit.Client.Web.BlazorUI + Bit.Client.Web.BlazorUI.Tests's build is not broken and tests are getting passed correctly after every PR which affects any file under src\Client\Web

**Comment by msynk** [comment]
+1

**Comment by FarhadGhE** [comment]
I'll handle this. I think it needs 2 hours of work. I will address the issue on Thursday or Friday.

**Comment by msynk** [comment]
is this issue still open and not resolved yet?
