### ISSUE TITLE
The Diffrence Between jaysvcUtil and Bit Html Client Proxy Generator

### ISSUE THREAD

**Issue by rypedram** [bitfoundation/bitframework#23]
1.	Bit Code Generator does not generate some properties which are Required. 

2.	No support for concurrency mode in Bit
                      JaySvcUtilSample: 
                              Version: {
                                              "concurrencyMode": $data.ConcurrencyMode.Fixed
                                             }

3.	Enum properties have two types of fields: Index & Value (JaySvcUtil)
                              Bit Sample:
	                               { name : 'Man' , value : "Foundation.Test.Model.Dto.TestGender'Man'" },
                             JaySvcUtil Sample:
                                       { "name": "Man",  "index": 0, "value": 3 },

4.	Bit Code Generator does not generate "Reflect define Metadata"
                       JaySvcUtil Sample:
                                      Reflect.defineMetadata("O1", ["Version"],  types["Entity"].prototype)

5. Bit Code Generator, Generate Action & Function In Camel Case Format

**Comment by ysmoradi** [comment]
Lets start with Index of Enum & Concurrency attribute! 💃
