### ISSUE TITLE
Buttons can be contained descendant elements

### ISSUE THREAD

**Issue by mirza-developer** [bitfoundation/bitframework#232]
Make BitButton and BitCompoundButton able to have descendant elements like img, a or bit components

**Comment by mirza-developer** [comment]
Would you mind just use bit components as descendant elements , like  BitLink ,BitImage?
Children HTML elements seem inaccessible from code (also from js because they don't render)
@ysmoradi

**Comment by ysmoradi** [comment]
I'm unable to understand what you mean. Try to call you soon

**Comment by mirza-developer** [comment]
I mean to create some common components that use in button like BitImage and BitLink (already have this) and make user able to use them as children components of buttons instead of all elements
