### ISSUE TITLE
Capture other html attributes

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#274]
It is a best practice to allow the component to capture other HTML element attributes that are not specified in Blazor code.
maybe through a Parameter with (CaptureUnmatchedValues = true) which could be named "Attributes".

**Comment by ysmoradi** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#avoid-attribute-splatting-with-captureunmatchedvalues

**Comment by msynk** [comment]
yeah, it is correct that this feature is a performance hit, so I updated the description.
But the requirement is still valid in my opinion. maybe we need a better solution to capture these attributes, in order to create an approach to set all other attributes which may not be available through Blazor code yet.

**Comment by ysmoradi** [comment]
Using @attributes we can achieve followings without performance penalty:

```html
<BitButton InputAttributes="@(new Dictionary<string, object> { { "test", 2 }, { "aria", "night" } })" />
```

https://www.pragimtech.com/blog/blazor/blazor-attribute-splatting/
