### ISSUE TITLE
Minimum requirements to build source code

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#305]
What are the "minimum requirements" in order to build the source code from scratch?
- Visual Studio version
- .Net version
- OS version
- Git version
- ...

**Comment by ysmoradi** [comment]
I think we need to discuss the development environment.
Build requires .net sdk only.

**Comment by msynk** [comment]
sure.
maybe we need to change this issue to a complete README.md with multiple required parts. (eg. introduction, requirements, build, test, contribution guide, ...)

**Comment by msynk** [comment]
I'm closing this issue in favor of the new and more polished issue (#339)
