### ISSUE TITLE
Improve ElementAttributeBuilder Reset usage

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitframework#322]
Before resetting classbuilder or stylebuilder, check that the Reset method is called if the value has really changed

for example, change this code

` [Parameter]
        public BoxSide BoxSide
        {
            get => boxSide; set
            {
                boxSide = value;
                ClassBuilder.Reset();
            }
        }`

to the following code:

`[Parameter]
        public BoxSide BoxSide
        {
            get => boxSide;
            set
            {
                if (boxSide != value)
                {
                    boxSide = value;
                    ClassBuilder.Reset();
                }
            }
        }`

**Comment by ysmoradi** [comment]
Builders are not too slow. And I think it's not required.
