### ISSUE TITLE
Watch mode keeps getting restarted because of continuous change in Component.razor.css!

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#336]
In the following image the issue is shown clearly:
![image](https://user-images.githubusercontent.com/6169846/116792876-a7cfbf80-aad8-11eb-8c47-a5290fc59be4.png)
But in reality, there are no changes in the file itself. 
Is this a hidden bug or something else that went wrong?

**Comment by ysmoradi** [comment]
Just replace Delegate.SassBuilder with LibSassBuilder
