### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by khashayar-pakkhesal** [bitfoundation/bitframework#349]
The project name is not business-friendly, I may suggest something like BitBlazor would be better for commercial purposes.

**Comment by msynk** [comment]
Although you are not wrong about the name not being business-friendly, we have to consider the overall state of the bitframework.
The framework itself consists of multiple modules which are developed in the same repository (marketing reasons).
These modules do not have separate and unique identities from each other, and they are being developed under a unified concept named "bit".
So assigning unique names to each of these modules does not make sense. 
Hense I'm closing this somehow correct issue for now.
