### ISSUE TITLE
Missing font in landing page of Playground project

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#352]
It seems after merging a new PR the main page style missed a font.
The below image shows the issue:
![image](https://user-images.githubusercontent.com/6169846/116978619-36129400-acd9-11eb-8a59-2e72fdfa4ceb.png)

**Comment by khashayar-pakkhesal** [comment]
After removing 
* {
    font-family: FluentFont;
}
from general.fluent.scss some parts of our code are font less I think for this issue first we have to find a general font for our website (exclude the components) and the assign it

**Comment by msynk** [comment]
I think it's best, for now, to bring back that font to the main page until the new design arrives.
