### ISSUE TITLE
Fix BitButton width and height as child of BitMessageBar

### ISSUE THREAD

**Issue by mirza-developer** [bitfoundation/bitframework#369]
In new changes on css styles, BitButtons styles for MessageBar that wrote in Messagebar sass file works with problem in width and height of button

**Comment by khashayar-pakkhesal** [comment]
we checked this component and it needs more consideration on properties and styles including this issue with width and height of the button so I created another issue that includes this particular issue  
you can see it [here](https://github.com/bitfoundation/bitframework/issues/393)

**Comment by msynk** [comment]
I'm closing this issue in favour of the newly created one (#393)
