### ISSUE TITLE
Missing samples of MessageBar component

### ISSUE THREAD

**Issue by msynk** [bitfoundation/bitframework#386]
there are some samples in the Microsoft Fluent UI components demo page which are not implemented in the Component.razor page.

https://developer.microsoft.com/de-de/fluentui#/controls/web/messagebar

![image](https://user-images.githubusercontent.com/6169846/118157322-a931ae00-b42f-11eb-9d11-521a3f29794b.png)

**Comment by mr-rahimi** [comment]
@msynk  I am working on this issue, please move it to InProgress to avoid replication. I don't know how to do that
