### ISSUE TITLE
Missing some features in textfield component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#397]
Multiline non-resizable
Multiline with auto adjusting height
Switches from single to multiline if more than 50 characters are entered
Underlined and borderless TextFields
TextField maskes
TextField with prefix and/or suffix
TextFields with custom rendering

https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

**Comment by ysmoradi** [comment]
Shall we use checkboxes at least?

- [ ] 1
- [X] 2
- [ ] 3

@msynk @SomayeEbrahimi

**Comment by msynk** [comment]
I think as we are attempting to resolve all parts of this issue in one PR, it is not required.

**Comment by zoha-shobbar** [comment]
there are some features that must add to BitTextField :
- label
- required
- error message
- description
- defaultValue
- onGetErrorMessage
- validateOnFocusIn
- validateOnFocusOut
- deferredValidationTime
