### ISSUE TITLE
Add validation attributes in textfield and checkbox components

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#398]
Textfield : https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield
- TextField error message variations

Checkbox : https://developer.microsoft.com/en-us/fluentui#/controls/web/checkbox
- Required

**Comment by msynk** [comment]
All validations in HTML Form related components (inputs) are postponed to the next phase of development.
So I'm closing this issue for now.
