### ISSUE TITLE
Error : Cant Resolve Type (Xamarin.Forms)

### ISSUE THREAD

**Issue by matinfathi19** [bitfoundation/bitframework#427]
hi bro
I installed  Bit.Client.Xamarin.Controls (ver  7.0.0) by Nuget In My Xamarin.Forms Project (.NetStandard 2)
and then added Its NameSpace in Page1.Xaml Which is My start page in App.xaml
But On Rebuilding The Project I Have An Error : Cant Resolve Type
Lock At Picture :
![error](https://user-images.githubusercontent.com/63930777/119532478-29de9b80-bd9a-11eb-8c85-78c9972ebd7a.png)
 How To Solve This ?

**Comment by ysmoradi** [comment]
Have you applied these configurations carefully?
https://bitfoundation.gitbook.io/bit-docs/xamarin-client-intro/getting-started

**Comment by matinfathi19** [comment]
I Forgot To Insert This Line After InitializeComponent() In App.cs
==>> BitCSharpClientControls.Init();
Now Everything Is Ok
Thanks  Jone Deeel . Bargharar Bashi.

**Comment by ysmoradi** [comment]
You can't delete that line and achieve expected results.
Have you added noda namespace to xaml usings?

https://github.com/bitfoundation/bitframework/blob/develop/Samples/CSharpClientSamples/Controls.Samples/Samples/BitDateTimePickerSampleView.xaml#L7

```xaml
xmlns:noda="clr-namespace:NodaTime;assembly=NodaTime"
```

**Comment by matinfathi19** [comment]
Now Every Thing Is Ok .
Thanks Joneh Del.
