### ISSUE TITLE
Error On x:Name="ElementName" (Xamarin.Forms)

### ISSUE THREAD

**Issue by matinfathi19** [bitfoundation/bitframework#428]
I have a problem on set x:Name="Element1" For all Bit controls

everything is ok with this code below (Page.Xaml)
```xml
<bit:BitDateTimePicker   
    Culture="Fa"
    DateTimeDisplayFormat="dd MMM yyyy"
    FlowDirection="RightToLeft"
    CalendarSystem="{x:Static noda:CalendarSystem.PersianArithmetic}" />
```

But the build would fail on the following statement:
```xml
<bit:BitDateTimePicker   
    x:Name="Element1"
    Culture="Fa"
    DateTimeDisplayFormat="dd MMM yyyy"
    FlowDirection="RightToLeft"
    CalendarSystem="{x:Static noda:CalendarSystem.PersianArithmetic}" />
```
![error](https://user-images.githubusercontent.com/63930777/119965838-f3826580-bfbf-11eb-9606-19b3b6cd8588.png)

the following 2 errors appeared:
1- InitializeComponent() at the constructor of Page.cs
2- in Page.xaml

I want to set the property Name for the element to get the current value  By  "this.ElemntName.Text"

Any Idea?

**Comment by msynk** [comment]
I edited the issue's description in order to improve its clearness

**Comment by ysmoradi** [comment]
It's an issue with XF itself.
Please use regular usings in your xaml instead of xmlns:bit="https://bit..."
Or better, use MVVM approach

**Comment by matinfathi19** [comment]
MVVM approach Solved The Problem.
What do you mean of 'regular using'?

**Comment by matinfathi19** [comment]
Hi Agin
Loock At This Code In Page.Xaml which every thing is ok
![Untitled](https://user-images.githubusercontent.com/63930777/121743190-35f68700-cb16-11eb-89db-2deec109c255.png)
And Now This One In Page.CS
![Untitled2](https://user-images.githubusercontent.com/63930777/121743295-64746200-cb16-11eb-8005-653b6c2019be.png)
When Move Codes To .CS The Attribute Calender System Dosnt Work
As I Said Before I Forced To Create MyCalender In .CS File Becuse Couldnt Set The X:Name="BitAZ" in .Xaml File And Then Call It By This.BitAZ But in .CS File I Would Have This.BitAz Without Problem.
Help Bro.

**Comment by matinfathi19** [comment]
any idea?????

**Comment by rypedram** [comment]
https://github.com/bitfoundation/bitframework/issues/195#issuecomment-660788466
https://github.com/bitfoundation/bitframework/issues/179#issuecomment-569955092

**Comment by matinfathi19** [comment]
> [#195 (comment)](https://github.com/bitfoundation/bitframework/issues/195#issuecomment-660788466)
> [#179 (comment)](https://github.com/bitfoundation/bitframework/issues/179#issuecomment-569955092)

Thanks
It Solved Problem
