### ISSUE TITLE
BitDropDown direction of opening the callout based on its position

### ISSUE THREAD

**Issue by mirza-developer** [bitfoundation/bitframework#430]
BitDropDown should automatically check its position and the available space on the screen to calculate the correct direction to open in order to show a full view of the callout element which is not applying for now. an example of this issue is showing in the following image:

![image](https://user-images.githubusercontent.com/6169846/120597253-13030d80-c45a-11eb-878e-be18e6a233b7.png)

**Comment by msynk** [comment]
I've updated the issue for better clarity
