### ISSUE TITLE
Add some features on BitButton Component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#443]
- Add Loading attribute
Add Loading attribute to add spinners within buttons to indicate an action is currently processing or taking place and user can change it's position.

- Add Size attribute
Add Size attribute : Small, Medium, Large 

- Add Outlined and Borderless button

**Comment by msynk** [comment]
Are these properties from the Microsoft Fluent UI library?

**Comment by SomayeEbrahimi** [comment]
No, But I thought we already have some items that need for these features, like a spinner for loading, so added this issue.

**Comment by msynk** [comment]
because we are not going to implement anything more than the Fluent UI spec unless we discuss otherwise, I'm going to close this issue for now.
