### ISSUE TITLE
Add Button group component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#444]
Group buttons together on a single line

![groupbtn](https://user-images.githubusercontent.com/46419023/121225679-025df780-c89f-11eb-9c12-be72d29d5b21.PNG)

**Comment by msynk** [comment]
Hmm, is it in the Microsoft Fluent UI library?

**Comment by SomayeEbrahimi** [comment]
No (:

**Comment by msynk** [comment]
so Unfortunately, I'm going to close this issue for now :)
I'm sorry
