### ISSUE TITLE
Missing some features in ChoiceGroup Component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#469]
- ChoiceGroup with custom option rendering
- ChoiceGroup with images
- ChoiceGroup with icons
- DefaultSelectedKey : The key of the option that will be initially checked (string, int) attribute.

Based on : https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup

**Comment by zoha-shobbar** [comment]
this issue gets fixed in the #697 pull request and should get closed
