### ISSUE TITLE
Multi-select dropdown should not be closed when we click on items

### ISSUE THREAD

**Issue by HamedMoghadasi** [bitfoundation/bitframework#528]
base on [fluent UI](https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown), When we select an item in the multi-select dropdown, it should stay open.

**Comment by msynk** [comment]
please provide a simple description :)

**Comment by SomayeEbrahimi** [comment]
The sample of issue:

![select](https://user-images.githubusercontent.com/46419023/127888570-61670b47-6e0b-4f4d-a382-ee98585586c0.gif)

**Comment by maryamhdr** [comment]
This issue is fixed in #764
