### ISSUE TITLE
BitNav should be scrollable in component page

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#546]
On the Components page, BitNav must be scrollable, now the items will be hidden as they are expanded as shown in the following image:
![image](https://user-images.githubusercontent.com/62525123/124261650-49f63d00-db46-11eb-9749-85589da5418c.png)

**Comment by zoha-shobbar** [comment]
On the Components page, BitNav must be scrollable, now the items will be hidden as they are expanded as shown in the following image:
![image](https://user-images.githubusercontent.com/62525123/124261650-49f63d00-db46-11eb-9749-85589da5418c.png)

**Comment by Md23Mh** [comment]
This issue is solved in #738
