### ISSUE TITLE
Missing some features in BitSearchBox component 

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#581]
there are some features that must add to BitSearchBox :

- defaultValue
- OnChange event that works on onInput event in the text input
- OnChanged event that works on onchange event in the text input 
- showIcon

**Comment by msynk** [comment]
the "OnChanged" event is obsolete:
![image](https://user-images.githubusercontent.com/6169846/125479031-31521ee3-f48a-44a7-9d3d-f4a3c165b089.png)
so it should not be implemented.
