### ISSUE TITLE
Missing some features in BitSpinButton component

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#582]
there are some features that must add to BitSpinButton :

- precision
- title
- decrementButtonAriaLabel
- decrementButtonIcon
- incrementButtonIcon
- incrementButtonAriaLabel
- decrementButtonAriaLabel
- ariaLabel
- ariaPositionInSet
- ariaSetSize
- ariaValueNow
- ariaValueText
- downArrowButtonStyles
- iconButtonProps
- iconProps
- onBlur
- onDecrement
- onFocus
- onIncrement
- onValidate

**Comment by maryamhdr** [comment]
I will fix this issue in #679
