### ISSUE TITLE
Missing some implementations in BitNav

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#589]
in Fluent UI nav, there are two objects for declaring link items: NavLinkGroup and NavLink. in every NavLinkGroup  we can have some NavLinks
as shown in the above picture there are different parameters  for these two types:
![image](https://user-images.githubusercontent.com/62525123/125533519-f9588652-1963-44c9-9b6b-e792f6f9f1e6.png)
![image](https://user-images.githubusercontent.com/62525123/125533626-f5ae2872-4532-4b5c-b3cf-e1c7506d7002.png)

and if we just use the links parameter in NavLinkGroup, we will not have border-bottom, and if we use the name parameter for it the border-bottom get to appear, and we must notice there can be a list of NavLinkGroups
![image](https://user-images.githubusercontent.com/62525123/125534091-8f0a6b5c-8b3f-4977-853e-f7ee7f0ffee1.png)

**Comment by msynk** [comment]
other than the missing parameters, the data structure used in the Fluent UI component is not useful for the BitNav, we can apply the required functionality with the current data structure in the BitNavLinkItem class.
I've discussed this with @FatemehNoroozi about the requirements and she will handle it.
So please update the issue or just close it and submit a new one.

**Comment by zoha-shobbar** [comment]
so as we discussed before, I think we need the IsGroup parameter to handle grouping and add the correct style for grouped list items (such as underlines in nested lists )
