### ISSUE TITLE
OnClick event in BitNav component didn't used in correct element

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#591]
in Fluent-UI Nav, there is no onClick event, but instead, there is onLinkClick & onLinkExpandClick and other click events are in NavLinks and LinkGroups. on click event implements in NavLinks, not Nav

**Comment by msynk** [comment]
what do you mean it does not work?
I've tested it and it's working fine for me.
please provide more data about the issue.

**Comment by zoha-shobbar** [comment]
the title and description of this issue have been modified
