### ISSUE TITLE
Incorrect style for nested links in BitNav component

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#592]
in Fluent UI the nested links show as bellow:
![image](https://user-images.githubusercontent.com/62525123/125535388-a1f622f4-1677-4f38-a62c-00c4d0e014f6.png)
but in BitNav we have redundant space between icon and link text, the icon must be beside the text  with a few spaces from icon of the parent item 
![image](https://user-images.githubusercontent.com/62525123/125535337-45ee30dc-8f0c-4a23-800f-348470de30fc.png)

**Comment by maryamhdr** [comment]
This issue is fixed in #830
