### ISSUE TITLE
Duplicate "bit-txt-disabled-fluent" CSS class insertion in BitTextFiled component

### ISSUE THREAD

**Issue by FatemehNoroozi** [bitfoundation/bitframework#604]
![Screen Shot 2021-07-18 at 5 33 51 PM](https://user-images.githubusercontent.com/30067345/126068157-1336bd43-0f77-4f12-9134-2e596bc0321d.png)

**Comment by zoha-shobbar** [comment]
this issue was fixed in pull request #691
