### ISSUE TITLE
Remove BitSpinButton additional space

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitframework#615]
It must be selected when double-clicked on the box

Fluent UI 
![image](https://user-images.githubusercontent.com/45947371/126439602-c723d555-1f49-4a44-b0d9-b4d71e3f7934.png)

In our case
![image](https://user-images.githubusercontent.com/45947371/126439676-97117d6c-06fc-479c-822c-4e26adf1f477.png)

**Comment by msynk** [comment]
this is not the issue of "double-click".
the issue is related to adding a "space" character after the initial number.
please correct the issue title and description accordingly.

**Comment by maryamhdr** [comment]
I will fix this bug in #679
