### ISSUE TITLE
Some attributes are not rendered in BitSpinButton

### ISSUE THREAD

**Issue by hamedhajiloo** [bitfoundation/bitframework#617]
**The following attributes are not rendered in this input**

- value
- valuemax
- type
- role
- aria-labelledby
- aria-valuenow
- aria-valuemin
- aria-valuemax
- aria-disabled
- data-lpignore

![image](https://user-images.githubusercontent.com/45947371/126457431-b5401bc9-1be0-418a-86c8-46974b97a52d.png)

**Comment by maryamhdr** [comment]
I will fix this issue in #679
