### ISSUE TITLE
On Focus border don't show in standard BitTextField

### ISSUE THREAD

**Issue by zoha-shobbar** [bitfoundation/bitframework#618]
wen BitTextFiled used in a simple way without any extra parameters, on focus border didn't show
![image](https://user-images.githubusercontent.com/62525123/126505163-a4213d7f-3ccf-4f18-b07d-b325b7777453.png)

, but when we use it with some icon,prefix,suffix it work fine
![image](https://user-images.githubusercontent.com/62525123/126505301-65a2f1a9-a408-4ef1-aa3a-b073bc01d193.png)

**Comment by msynk** [comment]
this is a duplicate & simpler version of #420
