### ISSUE TITLE
Missing some features on BitDropdown Component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#646]
According to https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown, some features missed on BitDropDown Component:

- Dropdown with an error message

![drp-error](https://user-images.githubusercontent.com/46419023/127957941-e826e282-a5d8-4560-99da-5dc9601e67eb.JPG)

- Required Dropdown
- Missing sample of opening Dropdown programmatically

![drp-req](https://user-images.githubusercontent.com/46419023/127958417-8e22c052-a65a-4cea-a5ec-39606395ae59.JPG)

- Customized Dropdown
- Custom width for dropdown (dropdownWidth parameters)

![drp-custom](https://user-images.githubusercontent.com/46419023/127958833-037dbe2a-f0ff-46a5-bbb6-8d34cc469b79.JPG)

And these parameters were missed too :

- defaultSelectedKeys: Keys that will be initially used to set selected items.
- multiSelectDelimiter: When multiple items are selected, this still will be used to separate values in the dropdown title.
- notifyOnReselect: Optional preference to have onChanged still be called when an already selected item is clicked in single select mode.
- responsiveMode: Pass in ResponsiveMode to manually overwrite the way the Dropdown renders.
- selectedKeys: Keys of the selected items.

**Comment by msynk** [comment]
Other than the "Required" parameter which is part of the Validation feature, the rest of the missing features are acceptable.

**Comment by maryamhdr** [comment]
This issue is very general and needs to be solved in several smaller issues.
