### ISSUE TITLE
a best way to reuse sync code in async method 

### ISSUE THREAD

**Issue by Alikhll** [bitfoundation/bitframework#7]
in bit-framework we've something like this following code
`public interface ISomeContract
{
    Task<int> SomeMethodAsync(CancellationToken cancellationToken);
    int SomeMethod();
}`
and suppose this implementation of it's contract
`public class SomeImplementation : ISomeContract
    {
        public int SomeMethod()
        {
            // lots of codes ...
            return 10;
        }
        public async Task<int> SomeMethodAsync(CancellationToken cancellationToken)
        {
            return SomeMethod();
            // another example: I can remove async modifier from SomeMethodAsync method and this following
            //try
            //{
            //    return Task.FromResult<int>(SomeMethod());
            //}
            //catch (Exception ex)
            //{
            //    return Task.FromException<int>(ex);
            //}
        }
    }`
we have some options to reuse sync method in async implementation
1)
`public Task<int> SomeMethodAsync(CancellationToken cancellationToken)
{
    return Task.Run(() => SomeMethod(), cancellationToken);
}`
2)
`public async Task<int> SomeMethodAsync(CancellationToken cancellationToken)
{
    cancellationToken.ThrowIfCancellationRequested();
    return SomeMethod();
}`
3)
`public Task<int> SomeMethodAsync(CancellationToken cancellationToken)
{
    if (cancellationToken.IsCancellationRequested)
    {
        return Task.FromCanceled<int>(cancellationToken);
    }
    try { return Task.FromResult(SomeMethod()); }
    catch (OperationCanceledException oce)
    {
        var canceledTaskBuilder = new TaskCompletionSource<int>();
        canceledTaskBuilder.SetCanceled();
        return canceledTaskBuilder.Task;
    }
    catch (Exception e)
    {
        return Task.FromException<int>(e);
    }
}`
more detail in this following:
[how to reuse sync code](http://stackoverflow.com/questions/40694256/how-to-reuse-sync-code-in-async-method-using-c-sharp)

**Comment by ymoradi** [comment]
@Alikhll Let me check

**Comment by ymoradi** [comment]
As I tested, Task.Run is checking all interesting parts of 3rd solution.
But as declared 'warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.' Using Task.Run might results in a non expected results. So, I'll rather to use 3rd solution only.
@Alikhll Could you please fork the project and apply this on DefaultBackgroundJobWorker.cs?
