### ISSUE TITLE
Misspellings in BitSlider.razor.cs

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#748]
There are some misspellings in `BitSlider.razor.cs` for some properties:

| Misspelling  | Correct spelling |
| ---------------------- |:---------------------:|
| fisrtInputValue          | firstInputValue        |
| secoundInputValue   | secondInputValue  | 

**Note:** For solving this issue, the mentioned properties must be renamed in both `BitSlider.razor.cs` and `BitSlider.razor`.

**Comment by msynk** [comment]
Thank you very much for reporting this issue. it will be fixed in the next release after the current refactoring phase.

**Comment by RezaKargar** [comment]
> Thank you very much for reporting this issue. it will be fixed in the next release after the current refactoring phase.

I have fixed the issue in the #749

**Comment by msynk** [comment]
I've seen the PR already and approved it, but it needs further investigations since an active refactoring process for this component is in progress.
