### ISSUE TITLE
Using PascalCase instead of camelCase for properties documentation in demo pages

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#751]
In demo pages of components which are mostly for documentation, in the section which is describing the parameters or properties, the parameters' name are written in camelCase, they are base on documentations of Microsoft's Fluent UI and thats if for React and in React we specify the parameters in camelCase.

I think the documentation must be exactly same as we use the parameters, in blazor we specify the parameters in PascalCase so documentation must be in PascalCase too.

**Comment by msynk** [comment]
Thanks a lot for reporting this issue. it will be fixed in the current sprint.
