### ISSUE TITLE
Selecting the multi-select dropdown's item by clicking on it's front

### ISSUE THREAD

**Issue by RezaKargar** [bitfoundation/bitframework#753]
I was wondering if make multi-select dropdown's item selected/unselected by clicking on its front,
I mean this:

<img src="https://user-images.githubusercontent.com/29206777/132053968-00082bdc-751b-49f3-9c4b-81d57616a910.gif" width="400" height="400" />

**Comment by RezaKargar** [comment]
In order to solve this issue I tried to change the `BitCheckbox.razor` and **onclick** to the root element:

![image](https://user-images.githubusercontent.com/29206777/132053673-92b366a5-0eae-448e-be64-0812f631f0c1.png)



But this change cause another problem, the caused problem is for `BitCheckbox` itself, this feature (multi-select dropdown's item by clicking on it's front) is actually a bug in BitCheckbox because the value checkbox must be changed only if the checkbox or its label has been clicked:
The created bug:

<img src="https://user-images.githubusercontent.com/29206777/132053988-499e80de-e4b5-473b-b586-6ab6c391de7b.gif" width="400" height="400" />


Any ideas how to solve this issue?

**Comment by msynk** [comment]
It seems this one needs further investigation. 
and since the BitDropDown is under heavy refactoring, this issue should be considered too.

**Comment by maryamhdr** [comment]
This issue is fixed in #760
