### ISSUE TITLE
Deform BitToggleButton samples in a 14 inches monitor 

### ISSUE THREAD

**Issue by mirza-developer** [bitfoundation/bitframework#827]
I checked the BitToggleButton page in playground project and got this in first sample:

<img width="943" alt="1" src="https://user-images.githubusercontent.com/43365143/134341741-23a85ea8-ea5f-43fe-95e1-a0f0c958f9f4.png">

OS: Windows 10 - Version 21h1 - Build 19043.1237
Device: ASUS Zenbook Flip UX463FL - ZQ (14 inches)
VS version: 2019 Enterprise Version 16.11.3

**Comment by mirza-developer** [comment]
Latest PR that merged in projects is #821

**Comment by msynk** [comment]
this issue is approved and only happening on the demo pages. It is fine on the Component page.
