### ISSUE TITLE
Add a new feature to specify vertical or horizontal alignment of ChoiceOptions

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitframework#865]
ChoiceOptions can be aligned either vertically or horizontally. There is no such feature in fluentui but we intend to implement it  for BitChoiceOption. So users will easily choose between these two states rather than having to write extra code for it.

![image](https://user-images.githubusercontent.com/26743275/136043620-08807899-6c8e-4ccb-9a5c-8c8f604ac8ae.png)
![image](https://user-images.githubusercontent.com/26743275/136044009-ad6f9afa-a36c-43f8-b162-5bcb749e6b37.png)

**Comment by maryamhdr** [comment]
this feature can be accessed easily using CSS customization.
this issue is fixed in #1125
