### ISSUE TITLE
Styling issue when hovering over ChoicOption

### ISSUE THREAD

**Issue by Md23Mh** [bitfoundation/bitframework#866]
There is a styling issue when we hover over ChoiceOptions as the following images indicate:

![image](https://user-images.githubusercontent.com/26743275/136044764-2e1b2919-ef2d-40c3-84d6-517ca272a7b4.png)
![image](https://user-images.githubusercontent.com/26743275/136045246-10d4ed50-c5bd-4a2b-9c05-9495248f7db3.png)

The icons and whatever inside of them shouldn't move and also there is a tiny little white circle right in the middle!

**Comment by maryamhdr** [comment]
this issue is fixed in #1125
