### ISSUE TITLE
Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

### ISSUE THREAD

**Issue by Salamesalehpour** [bitfoundation/bitframework#88]
I am building a bit framework sample but on line of "dependencyManager.RegisterDefaultWebApiConfiguration();" I get this error

System.IO.FileLoadException: 'Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ysmoradi** [comment]
1- Which version of visual studio is being used here? 2015 or 2017?

2- Have you installed .NET Core SDK 2.0?

3- Do you use new csproj format or old csproj format?
Old csproj format starts wtih:

```xml
<?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?>
<Project ToolsVersion=&quot;15.0&quot;  &quot;>Debug</Configuration>
    <Platform Condition=&quot; '$(Platform)' == '' &quot;>AnyCPU</Platform>
```

New csproj format starts with:

```xml
<Project Sdk=&quot;Microsoft.NET.Sdk&quot;>
  <PropertyGroup>
    <TargetFramework>net4.6.1</TargetFramework>
```

4- Do you use PackageReference or packages.config?

5- Which version of bit have you installed in your app?

6- Which platform have you targeted? .NET Core or .NET? which version?

7- What's a project type? ASP.NET | ASP.NET Core | Console ?

**Comment by Salamesalehpour** [comment]
1-2017
2-yes
3-old csproj format
4-PackageReference
5-I do not know. i get them from github then i build
6-.Net
7-Console

**Comment by ysmoradi** [comment]
You don't have to build bit framework's source code. We've released nuget packages. For example you can install Bit.WebApi & Microsoft.Owin.SelfHost and you're good to go as we showed in https://docs.bit-framework.com/docs/bit-server-side/web-api.html#getting-started
Our nuget packages's requirements such as System.Net.Http are described very well

**Comment by ysmoradi** [comment]
Put following file next to your solution file, then open visual studio and in nuget package's manager, you can see bit too. https://github.com/bit-foundation/bit-framework/blob/master/Nuget.Config

**Comment by Salamesalehpour** [comment]
Thanks a lot dear mr.Moradi. Put i want to trace bit framework. how can i do?

**Comment by ysmoradi** [comment]
You can do that by resharper + we've a plan to add support for git link

**Comment by ysmoradi** [comment]
By using latest version of visual studio & bit nuget packages, you can step into bit framework codes easily :-)

If you're using bit in full net framework based app, first check "Suppress JIT optimization on module Load." in visual studio settings.
