### ISSUE TITLE
Add anchor navigation feature to BitLink component

### ISSUE THREAD

**Issue by SomayeEbrahimi** [bitfoundation/bitframework#972]
This would allow you to easily link directly to each html element on the page.

Using `a` tag  for this purpose in blazor have a problem. The problem with anchor links is that when you click on them, the page won’t scroll to the element you’ve specified in the link. Anchor links will always take you to the top of the front page of your application.

**Comment by msynk** [comment]
please also provide the article's link that discussed this issue extensively.
